# Site settings
title: Practice Like You Play
email: MarkBruns@MarkBruns.com
description: Eat Your Own Dogfood
twitter_username: MarkBruns
github_username:  PLYP-US

# Build settings
markdown: kramdown
