# Site settings
title: AZYNCH Action
email: MarkBruns@MarkBruns.com
description: Embrace asynchronicity; build communicating and sharing discipline...reduce commuting, meetings and waste.
twitter_username: MarkBruns
github_username:  AZYNCH

# Build settings
markdown: kramdown
