# Site settings
title: PLYP.us
email: MarkBruns@MarkBruns.com
description: Practice Like You Play ... Eat Your Own Dogfood
twitter_username: MarkBruns
github_username:  plyp-us

# Build settings
markdown: kramdown
