# Site settings
title: AZYNCH Action
email: Z@azynch.com
description: Embrace asynchronicity; build communicating and sharing discipline...reduce commuting, meetings and waste.
twitter_username: QualityFellow
github_username:  AZYNCH

# Build settings
markdown: kramdown
