# Site settings
title: AZYNCH
email: Z@azynch.com
description: Embrace asynchronicity; improve communication disciplines to reduce commuting, meetings, waste.
twitter_username: QualityFellow
github_username:  AZYNCH

# Build settings
markdown: kramdown
